server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/sametozalp/socialmedia-config.git"
          default-label: "main"
          skip-ssl-validation: true
          username: "sametozalp"
          password: ${GITHUB_KEY}